version: '3.9'
services:
  client:
    build: ./client
    ports:
      - '8080:80'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: todo
      DB_USER: todorole
      DB_PASSWORD: 12345
    depends_on:
      - database
  database:
    image: "postgres:15.3"
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: todo
      POSTGRES_USER: todorole
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:


networks:
  default:
    name: todo-network
